services:
  # Servicio único (Rasa + Actions en un contenedor)
  - type: web
    name: chatbot-postgrados-ud
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5005
      - key: APEX_API_URL
        value: https://oracleapex.com/ords/udchatbot/chatbot
      - key: APEX_TIMEOUT
        value: 60
      - key: ENABLE_CACHE
        value: "True"
      - key: CACHE_TTL
        value: 3600
    buildCommand: pip install -r requirements.txt